### ISSUE TITLE
Failing to publish hex release

### ISSUE THREAD

**Issue by tonyvanriet** [NFIBrokerage/hummingbird#30]
with the update to v1.0.1, I'm seeing failures to publish the hex package.
this same command and same hex key is used in other projects that have successfully published recently.

https://github.com/NFIBrokerage/hummingbird/actions/runs/3108562476/jobs/5038082242

```
Publishing failed

account not authorized for this action
Error: Process completed with exit code 1.
```

suppose a next step is completely update the CI code here to match newer libraries.

that, or this difference in the hex owner is an important difference.
hummingbird has @bjornrud as the owner while the other public lib that successfully published has mike-davis and cuatroderek as owners.

**Comment by bjornrud** [comment]
Didn't change anything on my end, so assuming this is weather related, or this wasn't uncovered through infrequent release?  Better idea @tonyvanriet ?

**Comment by bjornrud** [comment]
Connects #28

**Comment by tonyvanriet** [comment]
oh yeah, #28 could explain it. sounds like michael changed to the cuatroderek key from the org secrets like the other libraries use, but we'd need to do this ownership migration to enable publishing again.

**Comment by bjornrud** [comment]
Lemme see if anything's still using it.  Could solve this by just archiving repo, since isn't part of main observability stack, and structured logging was unlocked.

**Comment by bjornrud** [comment]
Yep, plenty.  Didn't expect that.  Switching computers...

**Comment by bjornrud** [comment]
https://hex.pm/packages/hummingbird showing 1.0.2 owned by cuatro published by cuatroderek.  

Now for the scouting :broom:
